# This is a basic workflow to help you get started with Actions

name: Build_zSMTH_APK

# Controls when the action will run.
# Now configured to be manually triggered using the workflow_dispatch event
on:
  workflow_dispatch:
    inputs:
      reason:
        description: "构建原因"
        required: false
        default: "手动触发构建"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-outs your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout codes
        uses: actions/checkout@v2
        with:
          fetch-depth: "0" # 0 indicates all history, this is needed for git revision

      # https://github.com/actions/setup-java
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Assemble Release APK
        run: ./gradlew assembleRelease --stacktrace

      # 上传构建产物作为工作流产物
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: zsmth-apk
          path: ./app/build/outputs/apk/release/*.apk
          retention-days: 90
